name: socialapp
description: A new Flutter project.

version: 2.0.1+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^1.2.4
  flutter_svg: ^0.17.4
  pin_entry_text_field: ^0.1.4
  story_view: ^0.11.4
  image_picker: ^0.6.7+17


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: 'ArialBold'
      fonts:   
        - asset: lib/assets/fonts/arialBold.ttf

    - family: 'ArialSemiBold'
      fonts:   
        - asset: lib/assets/fonts/arialSemiBold.TTF

    - family: 'ArialMedium'
      fonts:   
        - asset: lib/assets/fonts/arialMedium.ttf
          
    - family: 'ArialRegular'
      fonts:   
        - asset: lib/assets/fonts/arialRegular.ttf


  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/addicon.png
    - lib/assets/icons/drawer.png
    - lib/assets/icons/home.png
    - lib/assets/icons/search.png
    - lib/assets/icons/fav.png
    - lib/assets/icons/profile.png
    - lib/assets/icons/logo.png
    - lib/assets/icons/logo.svg
    - lib/assets/icons/searchfield.png
    - lib/assets/images/user.png
    - lib/assets/images/user1.png
    - lib/assets/images/u2.png
    - lib/assets/images/u3.png
    - lib/assets/images/u4.png
    - lib/assets/images/u5.png
    - lib/assets/images/u6.png
    - lib/assets/images/u7.png
    - lib/assets/images/u8.png
    - lib/assets/images/u9.png
    - lib/assets/icons/comment.png
    - lib/assets/icons/share.png
    - lib/assets/icons/camera.png
    - lib/assets/icons/addfriend.png
    - lib/assets/icons/menuicon.png
    - lib/assets/images/girl.png
    - lib/assets/images/camera.png
    - lib/assets/icons/backarrow.png
    - lib/assets/images/story.png
    - lib/assets/icons/smiley.png
    - lib/assets/icons/Aa.png
    - lib/assets/icons/paint.png

















  